public class ExpsoureRequest {    
    
    //public List<Request> exposurerequests = new List<Request>();
    //
    //
   		public Double loanAmount;
        public String loanId;
        public String borrowerType;
        public Double interestRate;
        public String paymentFrequency;
        public String paymentType;
    	public String borrower;
        public Double totaldirect = 5;
    	public Double totalindirect = 6;
    /*public class Request{
        public Double loanAmount;
        public String loanId;
        public String borrowerType;
        public Double interestRate;
        public String paymentFrequency;
        public String paymentType;
    }*/

}